[package]
name = "auks-spank"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
auks-client = { path = "../auks-client" }
auks-config = { path = "../auks-config" }
auks-cred = { path = "../auks-cred" }
auks-krb5 = { path = "../auks-krb5" }
auks-spank-sys = { path = "../auks-spank-sys" }
libc = "0.2"

[lints]
workspace = true
